adding section for rewards option skeleton plus related CSS
CodingForProduct/tap_rewards pull request #34
Opened 2017-07-14 05:39 UTC by carolinambravo

@lisaluther here is the section mentioned for the dashboard / rewards options. Had to practice committing again while fresh! I wasn't entirely sure how to add the CSS part so please review this as well and make sure it makes sense how I added it to the CSS sheet. Thanks!

2017-07-15 23:18 UTC, Cindywangtelanoff commented
@lisaluther Can we merge @carolinambravo  onto your dashboard page or you want to create your own?

2017-07-16 02:10 UTC, tinuola approved these changes

2017-07-16 02:15 UTC, tinuola requested changes
@carolinambravo Looks like there's an extra div row missing in the dashboard.ejs file, in the rewards-option section. If you add up all the "cols" you get 24 in that section. Should be 12 and 12, so there's an extra row missing for the 2nd set of 12.

2017-07-17 03:40 UTC, closed without merging

2017-07-17 03:41 UTC, tinuola commented
@carolinambravo Main dashboard branch has been updated, so this pull request is obsolete. I'm also deleting the branch (your copy) off github.